### ISSUE TITLE
Too 133t

### ISSUE THREAD

**Issue by axxo1337** [call-042PE/PyInjector#1]
This is too leet, i'm sorry but such good work can't be as 133t as it is. Help me make roblox paste in python please and i won't report you from cheating the code

**Comment by call-042PE** [comment]
I can help you with ur roblox paste but you have to install windows xp with tor vpn via ssh with ftp port enabled so the fbi doesnt recognize u and also you need notepad version 1337 cracked by xXxF0rtnitePast3rUCXxX

**Comment by axxo1337** [comment]
i can do that. but pls tell me how to unpack vmp i need to crack aimware they have good lua script to hack roblox
